name: Build and Package Angular app v2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

      run_optional_job:
        description: 'Run the optional third job?'
        required: false
        default: false
        type: boolean  

jobs:
  build-package:
    name: Build and Package
    runs-on: ubuntu-latest
    environment: build-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build
        
  upload-dist:
    name: Upload dist folder
    runs-on: ubuntu-latest
    needs: build-package
    environment: build-app
    steps:
      # Upload Angular dist folder as a GitHub artifact
      - name: Upload Angular Dist Folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          
  prepare-package:
    if: ${{ github.event.inputs.run_optional_job == true }}
    name: Prepare deployment package
    runs-on: ubuntu-latest
    environment: upload-artifact
    steps:
      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy

          # Copy Angular build output
          cp -r dist deploy/

          # Copy server.js, package.json, etc.
          cp artifacts/server.js deploy/
          cp artifacts/package.json deploy/

          if [ -d "artifacts/.ebextensions" ]; then
            cp -r artifacts/.ebextensions deploy/
          fi
          cd deploy
          zip -r ../deployment-package.zip .

      - name: Unzip and List Contents of Deployment Package
        run: |
          unzip -l deployment-package.zip

      - name: Upload Angular Dist Folder
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package-artifact
          path: deployment-package.zip
